# travis CI support (https://travis-ci.org)

language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=audiobookfinder

notification:
     email:
       on_success: always
       on_failure: change

jobs:
  include:
    - os : linux
      dist: xenial
      name: job_build_linux_16_04_stable
      env: UBUNTU_VER=LTS_16.04 TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - os : linux
      dist: xenial
      name: job_build_linux_16_04_nightly      
      env: UBUNTU_VER=LTS_16.04 TARGET=x86_64-unknown-linux-gnu
      rust: nightly
  #- os: osx
  #  env: TARGET=x86_64-apple-darwin
  allow_failures:
    - rust: nightly

addons:
  apt:
    update: true
    packages:
      - p7zip-full  # 7z compression
      #  upx probably has too low version for lts 16.04 (https://github.com/upx/upx/issues/212)
      #- upx-ucl     # executable binary compression

# disable cache when needed
cache: cargo
# problem of caching problem within few days
# idea used from:
# https://github.com/rust-analyzer/rust-analyzer/blob/9a7db8fa009c612168ef16f6ed72315b5406ed09/.travis.yml#L2-L4
before_cache:
  - find ./target/debug -type f -maxdepth 1 -delete
  - rm -f ./target/debug/deps/*ra_*

before_install:
  - set -e

install:
  # pip for python needed for doc deployment
  - sudo -H pip install ghp-import
  # from japaric (https://github.com/japaric/trust)
  - bash ci/install.sh
  - source ~/.cargo/env || true
  # get upx directly from github
  - curl -L https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz > upx.xz
  - tar -xf ./upx.xz upx-3.95-amd64_linux/upx --strip-components=1 -C .
  - ./upx --version
  - echo $CRATE_NAME-$target-$TRAVIS_TAG
  # install xargo before / later inside ci/install.sh
  # force should be replaced by a check but travis is mysterious
  - cargo install xargo --force

script:
  # compile
  - xargo build --target $TARGET --release
  # run automated tests aka unit tests
  - cargo test
  # run compiled program with testaudio
  - ./target/$TARGET/release/$CRATE_NAME -- testaudio

after_script:
  - set +e

before_deploy:
  - cp target/$TARGET/release/$CRATE_NAME target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET
  - strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET -o target/release/$CRATE_NAME.stripped
#  - strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET -o target/release/$CRATE_NAME
  - ./upx --best target/release/$CRATE_NAME.stripped -o target/release/$CRATE_NAME
  - 7z a -r target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET-$TRAVIS_TAG.7z ./target/release/$CRATE_NAME ./README-release.md ./LICENSE
  - sha256sum target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET-$TRAVIS_TAG.7z > target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET-$TRAVIS_TAG.7z.sha256

deploy:
  # look at
  api_key: $gitHubToken
  overwrite: true
  file_glob: true
  file:
    - target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET-$TRAVIS_TAG.7z
    - target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET-$TRAVIS_TAG.7z.sha256
  provider: releases
  skip_cleanup: true
  on:
    repo: electricherd/audiobookfinder    
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
    branches:
      only:
        # release tags
        #- /^v\d+\.\d+\.\d+.*$/
        - master

after_success: |
  bash ci/document.sh

# don't build on appveyor configuration changes
ignore:
  - appveyor.yml
  - README.md
  - README-release.md
  - diag_architecture_general.svg
  - diag_architecture_general.xml

