# automatic build with travis
dist: trusty
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before-install:
  # libsodium is not part of trusty by default
  #- sudo apt-get install -y software-properties-common
  #- sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  #- sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo add-apt-repository ppa:james-page/0mq -y
  - sudo apt-get update -qq
  - sudo apt-get install libsodium-dev -y  
install:
  - sudo apt-get install -qq libavahi-compat-libdnssd-dev -y
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
