# travis CI support (https://travis-ci.org)

language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=audiobookfinder

notification:
     email:
       on_success: always
       on_failure: change

matrix:
  include:
    - os : linux
      dist: trusty
      env: UBUNTU_VER=LTS_14.04 TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - os : linux
      dist: trusty
      env: UBUNTU_VER=LTS_14.04 TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - os : linux
      dist: xenial
      env: UBUNTU_VER=LTS_16.04 TARGET=x86_64-unknown-linux-gnu
      rust: stable
    - os : linux
      dist: xenial
      env: UBUNTU_VER=LTS_16.04 TARGET=x86_64-unknown-linux-gnu
      rust: nightly
  #- os: osx
  #  env: TARGET=x86_64-apple-darwin
  allow_failures:
    - rust: nightly

addons:
  apt:
    update: true
    packages:
      - p7zip-full  # 7z compression
      - upx-ucl     # executable binary compression

# disable cache when needed
cache: cargo

before_install:
  - set -e

install:
  # pip for python needed for doc deployment
  - sudo -H pip install ghp-import
  # from japaric (https://github.com/japaric/trust)
  - bash ci/install.sh
  - source ~/.cargo/env || true
  # install xargo before / later inside ci/install.sh
  # force should be replaced by a check but travis is mysterious
  - cargo install xargo --force

script:
  # compile
  - xargo build --target $TARGET --release
  # run automated tests aka unit tests
  - cargo test
  # run compiled program with testaudio
  - ./target/$TARGET/release/$CRATE_NAME -- testaudio

after_script:
  - set +e

before_deploy:
  - cp target/$TARGET/release/$CRATE_NAME target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET
  - strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET -o target/release/$CRATE_NAME
  # upx yet disabled since causes segmentation faults
  #- strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET \
  #        -o target/release/$CRATE_NAME.stripped
  #- upx --ultra-brute target/release/$CRATE_NAME.stripped \
  #       -o target/release/$CRATE_NAME
  - 7z a -r target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.7z ./target/release/$CRATE_NAME ./README-release.md ./LICENSE
  - sha1sum target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.7z > target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.7z.sha1

deploy:
  # look at
  api_key: $gitHubToken
  overwrite: true
  file_glob: true
  file:
    - target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.7z
    - target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.7z.sha1
  provider: releases
  skip_cleanup: true
  on:
    repo: electricherd/audiobookfinder    
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
    branches:
      only:
        # release tags
        #- /^v\d+\.\d+\.\d+.*$/
        - master

after_success: |
  bash ci/document.sh
