# travis CI support (https://travis-ci.org)
dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=audiobookfinder

rust:
  - nightly
notification:
    slack:
      on_success: always
    email:
       on_success: always
       on_failure: change
matrix:
  include:
   #- env: TARGET=arm-unknown-linux-gnueabi (libsodium problem)
   - env: TARGET=armv7-unknown-linux-gnueabihf
   - env: TARGET=i686-unknown-linux-gnu
   #- env: TARGET=x86_64-apple-darwin
# disable cache for a small while
#cache: cargo

before_install:
  - set -e
  - rustup self update

install:
  # pip for python needed for doc deployment
  - sudo pip install ghp-import
  # from japaric (https://github.com/japaric/trust)
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - cargo build && cargo test && cargo run -- testaudio
after_script: set +e

deploy:
  github-token: ${gitHubToken}
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

after_success: |
  bash ci/document.sh
