dist: xenial
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
install:
  - sudo apt-get install -qq libsodium-dev -y
  - sudo apt-get install -qq libavahi-compat-libdnssd-dev -y
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
