dist: trusty
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before-install:
  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo apt-get update -q
  - sudo apt-get install -qq libsodium-dev -y
install:
  - sudo apt-get install -qq libavahi-compat-libdnssd-dev -y
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
