dist: trusty
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before-install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -q  
install:
  - sudo apt-get install -qq libavahi-compat-libdnssd-dev
  - sudo apt-get install -qq libsodium-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
