# travis CI support (https://travis-ci.org)
dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=audiobookfinder

rust:
  - nightly
  #- stable
notification:
    slack:
      on_success: always
    email:
       on_success: always
       on_failure: change
matrix:
  include:
   #- env: TARGET=aarch64-unknown-linux-gnu
   #- env: TARGET=arm-unknown-linux-gnueabi (libsodium problem)
   - env: TARGET=armv7-unknown-linux-gnueabihf
   #- env: TARGET=i686-unknown-linux-gnu
   - env: TARGET=x86_64-unknown-linux-gnu

   #- env: TARGET=x86_64-apple-darwin
   #   os: osx
# disable cache when needed
cache: cargo

before_install:
  - set -e
  - rustup self update

install:
  # pip for python needed for doc deployment
  - sudo pip install ghp-import
  # from japaric (https://github.com/japaric/trust)
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - PKG_CONFIG_ALLOW_CROSS=1 cargo build --target $TARGET --release
  - PKG_CONFIG_ALLOW_CROSS=1 cargo test
  - PKG_CONFIG_ALLOW_CROSS=1 cargo run --target $TARGET -- testaudio
  #- bash ci/script.sh
after_script:
  - set +e

before_deploy:
  # - sh ci/before_deploy.sh
  - cp target/release/$CRATE_NAME target/release/$CRATE_NAME-$TARGET
  - sha1sum target/release/$CRATE_NAME-$TARGET > target/release/$CRATE_NAME-$TARGET.sha1

deploy:
  # look at
  api_key: $gitHubToken
  file_glob: true
  file:
    - $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  #  - target/release/$CRATE_NAME-$TARGET.sha1
  on:
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
    #repo: electricherd/audiobookfinder
  provider: releases
  skip_cleanup: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

after_success: |
  bash ci/document.sh
