dist: trusty
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before-install:
  - sudo apt-get install -y software-properties-common
  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libsodium-dev -y
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
