# travis CI support (https://travis-ci.org)

language: rust
services: docker
sudo: required

matrix:
  include:
    - os : linux
      dist: trusty
      env: UBUNTU_VER=trusty TARGET=x86_64-unknown-linux-gnu
       #- env: TARGET=aarch64-unknown-linux-gnu
       #- env: TARGET=arm-unknown-linux-gnueabi (libsodium problem)
       #- env: TARGET=armv7-unknown-linux-gnueabihf
       #- env: TARGET=i686-unknown-linux-gnu
    - os : linux
      dist: xenial
      env: UBUNTU_VER=xenial TARGET=x86_64-unknown-linux-gnu
   #- env: TARGET=x86_64-apple-darwin
   #   os: osx

addons:
  apt:
    update: true
    
env:
  global:
    - CRATE_NAME=audiobookfinder

rust:
  #- nightly
  - stable
notification:
     email:
       on_success: always
       on_failure: change

# disable cache when needed
cache: cargo

before_install:
  - set -e
  # - rustup self update

install:
  # pip for python needed for doc deployment
  - sudo -H pip install ghp-import
  # from japaric (https://github.com/japaric/trust)
  - bash ci/install.sh
  - source ~/.cargo/env || true

script:
  - PKG_CONFIG_ALLOW_CROSS=1 cargo build --target $TARGET --release
  - PKG_CONFIG_ALLOW_CROSS=1 cargo test
  - PKG_CONFIG_ALLOW_CROSS=1 cargo run --target $TARGET -- testaudio
after_script:
  - set +e

before_deploy:
  - cp target/release/$CRATE_NAME target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET
  - sha1sum target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET > target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.sha1

deploy:
  # look at
  api_key: $gitHubToken
  file_glob: true
  file:
    - $CRATE_NAME-$TRAVIS_TAG-$UBUNTU_VER-$TARGET.*
    - target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET.sha1
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    #tags: true
    repo: electricherd/audiobookfinder
  provider: releases
  skip_cleanup: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

after_success: |
  bash ci/document.sh
