dist: trusty
language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
before-install:
  - sudo apt-get install -y software-properties-common
  - sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update -y
  - sudo apt-get install -qq libsodium-dev -y
install:
  - sudo apt-get install -qq libavahi-compat-libdnssd-dev -y
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
