version: "{build}"

image:
- Visual Studio 2017
- Ubuntu1804

environment:
  global:
    CRATE_NAME: audiobookfinder
    UBUNTU_VER: LTS_18.04
  matrix:
# don't use "configuration" variable in this file!!!
    - target: x86_64-unknown-linux-gnu
      ARCH: amd64
      type: Release
      CHANNEL: stable
      platform: x64
    - target: x86_64-pc-windows-msvc
      ARCH: amd64
      type: Release
      CHANNEL: stable
      platform: x64
      # versions for libs
      LIBSODIUM_WIN_VER: 1.0.17
      TAGLIB_WIN_VER: 2.1.0

matrix:
  exclude:
    - image: Visual Studio 2017
      target: x86_64-unknown-linux-gnu
    - image: Ubuntu1804
      target: x86_64-pc-windows-msvc

# build configuration, i.e. Debug, Release, etc.

cache:
  - '.cargo'

# scripts that are called at very beginning, before repo cloning
# ACCEPT_EULA for some windows packages .. whatever
init:
  - sh: sudo apt-get update
# comment next line for quick build
#  - sh: sudo DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y apt-get upgrade -yq
  - sh: sudo apt-get --yes install build-essential
  - sh: sudo apt-get --yes install libavahi-compat-libdnssd-dev
  - sh: sudo apt-get --yes install libsodium-dev
  - sh: sudo apt-get --yes install libtag1-dev libtagc0-dev
#  for deployment
  - sh: sudo apt-get --yes install p7zip-full upx-ucl

# scripts that run after cloning repository
install:
  #
  # shell: Linux
  #
  - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./rustup.sh
  - sh: sh ./rustup.sh -y 
# for debugging: ls -al
  - sh: source $HOME/.cargo/env
# it's a clean install so not needed: rustup update
# comment next line for quick build
#  - sh: rustup toolchain install nightly
  - sh: rustup target install $target
  #
  # cmd (powershell should only be triggered with windows build)
  #
  # trying NuGet and powershell for lib installation
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: nuget install taglib -Version %TAGLIB_WIN_VER%
  - cmd: nuget install libsodium -Version %LIBSODIUM_WIN_VER%
  - cmd: set SODIUM_LIB_DIR=%ProgramFiles(x86)%\Microsoft SDKs\NuGetPackages\libsodium\runtimes\win-x64\native
  - cmd: set SODIUM_STATIC=1
  - cmd: nuget locals all -list
   # old way test download https://libsodium.gitbook.io/doc/installation  
  #- cmd: appveyor-retry appveyor DownloadFile https://download.libsodium.org/libsodium/releases/libsodium-%LIBSODIUM_WIN_VER%-stable-msvc.zip -FileName libsodium.7z 
  #- cmd: 7z x -y libsodium.7z -oC:\build_libs\libsodium
  - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs
  - cmd: rustup-init.exe --default-host %target% --default-toolchain %CHANNEL% -y
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - cmd: del rustup-init.exe
  - cmd: rustc -Vv
  - cmd: rustup target install %target%  
  - cmd: cargo -V  

build_script:
# comment next line for quick build
#  - cargo build
  - sh: cargo build --release --target $target  
  - cmd: cargo build --release --target %target%

test_script:
# comment next lines for quick build  
#  - sh: cargo run --release --target $target -- testaudio
#  - sh: cargo test --release --target $target
  - sh: ./target/$target/release/$CRATE_NAME -- testaudio  

artifacts:
  - path: target/release/$CRATE_NAME-$UBUNTU_VER-$target.7z
    name: zippedFiles

  - path: target/release/$CRATE_NAME-$UBUNTU_VER-$target.7z.sha256
    name: shachecksum


after_build:
  - sh: cp target/$target/release/$CRATE_NAME target/release/$CRATE_NAME-$UBUNTU_VER-$target
  - sh: strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$target -o target/release/$CRATE_NAME
  # upx yet disabled since causes segmentation faults
  #- strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$TARGET \
  #        -o target/release/$CRATE_NAME.stripped
  #- upx --ultra-brute target/release/$CRATE_NAME.stripped \
  #       -o target/release/$CRATE_NAME
  - sh: 7z a -r target/release/$CRATE_NAME-$UBUNTU_VER-$target.7z ./target/release/$CRATE_NAME ./README-release.md ./LICENSE
  - sh: sha256sum target/release/$CRATE_NAME-$UBUNTU_VER-$target.7z > target/release/$CRATE_NAME-$UBUNTU_VER-$target.7z.sha256

deploy:
  # due to mutually exclusive branch and tagged (https://www.appveyor.com/docs/branches/)
  # 2 provider sections would be needed to have tagged and branch release, would be needed
  # but branch is not important since until now, only master is used
  provider: GitHub
  artifact: 
    -'zippedFiles'
    -'shachecksum'
  auth_token:
    # yes this is encrypted/signed by appveyor (from the github token)
    secure: aT3Xjbg4GSAJtYjhk7SrC1RInLV28rI6e64he6JClx2W09nToXvPyHr/zXc0tqPj
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true       # deploy on tag push only
    target: x86_64-unknown-linux-gnu

# don't build on travis configuration changes
skip_commits:
  files:
    - .travis.yml
#    - README.md
