version: "{build}"

image:
- Ubuntu2004
- Visual Studio 2017
- Ubuntu1804

environment:
  global:
    CRATE_NAME: audiobookfinder
    PACKAGE_NAME: adbflib
  matrix:
# don't use "configuration" variable in this file!!!
    - target: x86_64-unknown-linux-gnu
      UBUNTU_VER: LTS_18.04
      ARCH: amd64
      type: Release
      CHANNEL: stable
      platform: x64
    - target: x86_64-unknown-linux-gnu
      UBUNTU_VER: LTS_20.04
      ARCH: amd64
      type: Release
      CHANNEL: stable
      platform: x64
    - target: x86_64-pc-windows-msvc
      ARCH: amd64
      type: Release
      CHANNEL: stable
      platform: x64
      # versions for libs
      LIBSODIUM_WIN_VER: 1.0.17
      TAGLIB_WIN_VER: 2.1.0


matrix:
  exclude:
    - image: Visual Studio 2017
      target: x86_64-unknown-linux-gnu
    - image: Ubuntu1804
      target: x86_64-pc-windows-msvc
    - image: Ubuntu2004
      target: x86_64-pc-windows-msvc
    - image: Ubuntu1804
      UBUNTU_VER: LTS_20.04
    - image: Ubuntu2004
      UBUNTU_VER: LTS_18.04


#  allow_failures:
#    - target: x86_64-pc-windows-msvc

# build configuration, i.e. Debug, Release, etc.

cache:
  - '.cargo'

# scripts that are called at very beginning, before repo cloning
# ACCEPT_EULA for some windows packages .. whatever
init:
  - sh: sudo apt-get update
  - sh: sudo apt-get --yes install build-essential
  #  for deployment
  - sh: sudo apt-get --yes install p7zip-full # upx-ucl is now in install
  # for cargo-deb run (10 is the version number: taken from https://apt.llvm.org/) to LTS18 it's only 10
  - sh: sudo apt-get --yes install clang python3-lldb-10 llvm-7

# scripts that run after cloning repository
install:
  #
  # shell: Linux
  #
  # IMPORTANT: yet 3.96 somehow errors on LTS20 build, 3.95 NOT!! This is why 3.95 is used here
  - sh: curl -L https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz > upx.xz
  - sh: tar -xf ./upx.xz upx-3.95-amd64_linux/upx --strip-components=1 -C .
  - sh: ./upx --version
  - sh: echo $CRATE_NAME-$target-$APPVEYOR_REPO_TAG_NAME
  - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./rustup.sh
  - sh: sh ./rustup.sh -y 
# for debugging: ls -al
  - sh: source $HOME/.cargo/env
  # it's a clean install so not needed: rustup update
  - sh: rustup target install $target
  # install debian packager https://crates.io/crates/cargo-deb
  - sh: cargo install cargo-deb
  #
  # cmd (powershell should only be triggered with windows build)
  #
  # upx for windows
  - cmd: appveyor DownloadFile https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip
  - cmd: 7z e upx-3.96-win64.zip upx-3.96-win64\upx.exe
  - cmd: upx.exe --version
  - cmd: echo "%CRATE_NAME%-%target%-%APPVEYOR_REPO_TAG_NAME%"
  - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs
  - cmd: rustup-init.exe --default-host %target% --default-toolchain %CHANNEL% -y
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - cmd: del rustup-init.exe
  - cmd: rustc -Vv
  - cmd: rustup target install %target%  
  - cmd: cargo -V  

build_script:
# comment next line for quick build
#  - cargo build
  - sh: cargo build --bin $CRATE_NAME --release --target $target
  - cmd: cargo build --bin %CRATE_NAME% --release --target %target%

test_script:
  - sh: cargo test --bin $CRATE_NAME
  - cmd: cargo test --bin %CRATE_NAME%
  - sh: ./target/$target/release/$CRATE_NAME -- testaudio
  - cmd: target\%target%\release\%CRATE_NAME%.exe -- testaudio

after_build:
  - sh: LLVM_CONFIG_PATH=/usr/bin/llvm-config-7 cargo deb -p $PACKAGE_NAME --target=$target
  - sh: cp target/$target/debian/* $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.deb
  #
  - sh: cp target/$target/release/$CRATE_NAME target/release/$CRATE_NAME-$UBUNTU_VER-$target
  - sh: strip -s target/release/$CRATE_NAME-$UBUNTU_VER-$target -o target/release/$CRATE_NAME-$UBUNTU_VER-$target.stripped
  - sh: ./upx --best target/release/$CRATE_NAME-$UBUNTU_VER-$target.stripped -o target/release/$CRATE_NAME
  - sh: 7z a -r $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.7z ./target/release/$CRATE_NAME ./README-release.md ./LICENSE
  - sh: sha256sum $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.7z > $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.7z.sha256
# windows
  - cmd: copy "target\%target%\release\%CRATE_NAME%.exe" "target\release\%CRATE_NAME%-%target%-orig.exe"
  - cmd: upx --best "target\release\%CRATE_NAME%-%target%-orig.exe" -o "target\release\%CRATE_NAME%.exe"
  - cmd: 7z a -r "%CRATE_NAME%-%target%-%APPVEYOR_REPO_TAG_NAME%.7z" ".\target\release\%CRATE_NAME%.exe" ".\README-release.md" ".\LICENSE"
  - cmd: certUtil -hashfile "%CRATE_NAME%-%target%-%APPVEYOR_REPO_TAG_NAME%.7z" SHA256 > "%CRATE_NAME%-%target%-%APPVEYOR_REPO_TAG_NAME%.7z.sha256"

#test_script:
# comment next lines for quick build  
#  - sh: cargo run --release --target $target -- testaudio
#  - sh: cargo test --release --target $target
#  - sh: ./target/$target/release/$CRATE_NAME -- testaudio

artifacts:
  - path: "%CRATE_NAME%-%target%-%APPVEYOR_REPO_TAG_NAME%.7z"
    name: windowsBuild
  - path: "%CRATE_NAME%-%target%-%APPVEYOR_REPO_TAG_NAME%.7z.sha256"
    name: windowsSha
  - path: $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.7z
    name: linuxBuild
  - path: $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.7z.sha256
    name: linuxSha
  - path: $CRATE_NAME-$UBUNTU_VER-$target-$APPVEYOR_REPO_TAG_NAME.deb
    name: linuxDeb

deploy:
# due to mutually exclusive branch and tagged (https://www.appveyor.com/docs/branches/)
# 2 provider sections would be needed to have tagged and branch release, would be needed
# but branch is not important since until now, only master is used
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    # yes this is encrypted/signed by appveyor (from the github token)
    secure: r7fSlUlYmQ1WCJeuTZu8XnQ0n5QNvWb+eVX5lsowCbA9gLlq3DtIFiTSjXTXjs6V
  draft: false
  prerelease: false
  force_update: true
  on:
    # branch: master
    # something very wrong with tag "v0.1.19" it claims
    # says: "GitHub" deployment for branch "master" has been skipped because current branch is "v0.1.19"
    APPVEYOR_REPO_TAG: true       # deploy on tag push only


# don't build on travis configuration changes
skip_commits:
  files:
    - .github/
    - .travis.yml
    - android/
    - ci/
    - docs/
    - ios/
    - lib/
    - native/adbflib-ffi/
    - packages/
    - testaudio/
    - README.md
    - README-release.md
    - Makefile.toml
    - pubspec.yaml
