version: "{build}"

image:
  - Ubuntu1804

platform:
  - x64

environment:
  crate_name: audiobookfinder
  matrix:
    - target: x86_64-unknown-linux-gnu

# build configuration, i.e. Debug, Release, etc.
configuration:
#  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
# ACCEPT_EULA for some windows packages .. whatever
init:
  - sh: sudo apt-get update
# upgrade later when we know it works - sh: sudo ACCEPT_EULA=Y apt-get --yes
  - sh: sudo apt-get --yes install build-essential
  - sh: sudo apt-get --yes install libavahi-compat-libdnssd-dev
  - sh: sudo apt-get --yes install libsodium-dev
  - sh: sudo apt-get --yes install libtag1-dev libtagc0-dev

# scripts that run after cloning repository
install:
  - sh: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./rustup.sh
  - sh: sh ./rustup.sh -y 
# for debugging: ls -al
  - sh: source $HOME/.cargo/env
# it's a clean install so not needed: rustup update
  - sh: rustup toolchain install nightly
  - sh: rustup target install %target%


build_script:
  - sh: cargo build

test_script:
  - cargo build --release --target %target%
  - cargo run --release --target %target% 
  - cargo test --release --target %target%
  - ./target/%target%/release/%crate_name% -- testaudio
