[target.x86_64-unknown-linux-gnu]
image = "ci/docker/x86_64-unknown-linux-gnu/Dockerfile:0.1.13"
[target.armv7-unknown-linux-gnueabihf]
image = "ci/docker/armv7-unknown-linux-gnueabihf/Dockerfile:0.1.13"
