name: adbflib
description: A new flutter plugin project.
version: 0.0.6
author:
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  isolate: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.skroemeke.adbflib
        pluginClass: AdbflibPlugin
      ios:
        pluginClass: AdbflibPlugin
