name: adbflib
description: A new flutter plugin project.
version: 0.0.6
author:
homepage: "https://github.com/electricherd/audiobookfinder/tree/master/native/adbflib-ffi"

environment:
  sdk: ">=2.7.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: "^1.0.0"
  isolate: "^2.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.skroemeke.adbflib
        pluginClass: AdbflibPlugin
      ios:
        pluginClass: AdbflibPlugin
