//! This module just holds as a collection of all modules configuration.
//! Some configuration should be hold in its module but more general parts
//! (which later may be configurable by a config file) should be put here.

/// The network related configurations
#[allow(non_camel_case_types)]
pub mod net {
    /// MDNS service address space
    pub static MDNS_SERVICE_NAME: &str = "_http._tcp"; // "_tcp.local"

    pub static MDNS_REGISTER_NAME: &str = "adbf";
    pub static MDNS_PORT : u16 = 80;
    pub static MDNS_TIMEOUT_SEC : u16 = 5;

    pub static SSH_CLIENT_USERNAME : & str = "e";
    pub static SSH_CLIENT_AND_PORT : & str = "0.0.0.0:2222";
    pub static SSH_HOST_AND_PORT : & str = "127.0.0.1:2222";

    // key can be generated by
    // ssh-keygen -f ~/.adbf/client_key.priv -N 'adbf' -t ed25519
    pub static SSH_CLIENT_SEC_KEY_PATH   : &str = "/.adbf/client_key.priv";
    pub static SSH_CLIENT_SEC_KEY_PASSWD : &str = "adbf";

    pub struct changeable {

    }
}

/// The TUI related configurations of a more general purpose
pub mod tui {

    pub static ALIVE_REFRESH: u64 = 80;
}
