//! This module just holds as a collection of all modules configuration.
//! Some configuration should be hold in its module but more general parts
//! (which later may be configurable by a config file) should be put here.

/// The network related configurations
#[allow(non_camel_case_types)]
pub mod net {
    /// MDNS service address space
    pub static MDNS_SERVICE_NAME: &str = "_http._tcp"; // "_tcp.local"

    pub static MDNS_REGISTER_NAME: &str = "adbf";
    pub static MDNS_PORT : u16 = 80;
    pub static MDNS_TIMEOUT_SEC : u16 = 5;

    pub static SSH_CLIENT_USERNAME : & str = "e";
    pub static SSH_PORT : u16 =  2222;

    // key can be generated by
    // ssh-keygen -f ~/.adbf/client_key.priv -N 'adbf' -t ed25519

    /// private key path, relatively to env_home
    pub static SSH_CLIENT_SEC_KEY_PATH   : &str = "/.adbf/client_key.priv";
    pub static SSH_CLIENT_SEC_KEY_PASSWD : &str = "adbf";

    pub struct changeable {

    }
}

/// The TUI related configurations of a more general purpose
pub mod tui {
    pub static ALIVE_REFRESH: u64 = 80;
}

/// The data related configurations of a more general purpose
pub mod data {
    /// ignore those tree_magic extensions. like m3u
    pub static IGNORE_AUDIO_FORMATS : [&str;1] = ["x-mpegurl"];
}
