on: [push, pull_request]
# this from  from https://github.com/sunshine-protocol/sunscreen Appache 2.0 license
#

# name is (urlencode) connected to README.md svg badge (change it there as well)
name: iOS Build

jobs:
  ci:
    name: Compile and Build - iOS
    runs-on: macos-latest
    steps:
      # #################### build conditions
      - name: condition tagged
        id: cond_tagged_release
        # https://github.com/marketplace/actions/get-the-upload-url-for-a-release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: condition Release
        id: cond_release_text
        # https://github.com/marketplace/actions/release-with-commit
        uses: ChanTsune/release-with-commit@v1.0.0
        with:
          regexp: "Release (\\d+([.]\\d+)*)\n*((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$3"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ##################### setup build environment
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm/10.0
          key: ${{ runner.os }}-cached-llvm-10.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm/10.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Install WASM Target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target/aarch64-apple-ios
            target/x86_64-apple-ios
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Cargo Tools (cargo-make)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cargo-make

      - name: Install Cargo Tools (cbindgen, v0.14.4)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: cbindgen --version 0.14.4

      - name: Install Cargo Tools (dart-bindgen)
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: install
          args: dart-bindgen --features cli

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Install iOS Targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      # ############### Release/Debug build dependent
      - name: Run cargo make ios  - Release
        if: steps.cond_release_text.outputs.upload_url != null || steps.cond_tagged_release.outputs.tag_name != null
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: ios --profile release

      - name: Run cargo make ios  - debug
        if: steps.cond_release_text.outputs.upload_url == null && steps.cond_tagged_release.outputs.tag_name == null
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: make
          args: ios --profile debug

      - name: Build iOS App - release
        if: steps.cond_release_text.outputs.upload_url != null || steps.cond_tagged_release.outputs.tag_name != null
        run: flutter build ios --release --no-codesign --simulator

      - name: Build iOS App - debug
        if: steps.cond_release_text.outputs.upload_url == null && steps.tag.outputs.tag == null
        run: flutter build ios --debug --no-codesign --simulator


      # ####################### upload intermediate result dependent if release in text or tagged
      - name: Upload Release - Release in text
        id: upload-release-text-asset
        if: steps.cond_release_text.outputs.upload_url != null && steps.cond_tagged_release.outputs.tag_name == null
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.cond_release_text.outputs.upload_url }}
          asset_path: ./build/ios/iphoneos/Runner.app
          asset_name: adbfflutter-ios-intermediate.app
          asset_content_type: application/octet-stream

      - name: Upload Release - Release with tag
        id: upload-release-tagged-asset
        if: steps.cond_tagged_release.outputs.tag_name != null
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.cond_tagged_release.outputs.upload_url }}
          asset_path: ./build/ios/iphoneos/Runner.app
          asset_name: adbfflutter-ios-intermediate-${{ steps.cond_tagged_release.outputs.tag_name }}.app
          asset_content_type: application/octet-stream
