on: [push]
name: Prepare release
jobs:
  build:
    name: Prepare Release on github
    runs-on: ubuntu-latest
    steps:
      # #################### build conditions
      - name: vtag variable
        shell: bash
        run: echo "vtag=$(echo ${GITHUB_REF#refs/tags/} | awk '/v([0-9]+\.)+[0-9]+/{print $0}')" >> $GITHUB_ENV

      - name: Extractor for vtag env
        id: extract_tag
        shell: bash
        run: echo ::set-output name=tag::${{ env.vtag }}

      # ####################### upload release file description

      # https://github.com/marketplace/actions/create-a-release
      - name: Create Release
        if: steps.extract_tag.outputs.tag != null
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag }}
          release_name: Release ${{ steps.extract_tag.outputs.tag }}
          body_path: docs/changes.md
          draft: false
          prerelease: false